### ISSUE TITLE
Receiving message crashes Node-Red

### ISSUE THREAD

**Issue by BloodBlight** [Markoudstaal/node-red-contrib-discord-advanced#7]
First time using it (switched from node-red-contrib-discord), have my token setup, send a message to it expecting a debug message and instead got disconnected.  Checked the docker and it had crashed with: 

```
27 Sep 20:21:27 - TypeError: Cannot read property 'array' of undefined
    at Client.<anonymous> (/data/node_modules/node-red-contrib-discord-advanced/discord/discordMessage.js:34:77)
    at Client.emit (events.js:375:28)
    at MessageCreateHandler.handle (/data/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/data/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/data/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/data/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/data/node_modules/discord.js/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:375:28)
    at Receiver.receiverOnMessage (/data/node_modules/discord.js/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:375:28)
    at Receiver.dataMessage (/data/node_modules/discord.js/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/data/node_modules/discord.js/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/data/node_modules/discord.js/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/data/node_modules/discord.js/node_modules/ws/lib/receiver.js:74:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.socketOnData (/data/node_modules/discord.js/node_modules/ws/lib/websocket.js:864:35)
    at TLSSocket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@2.0.5 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
```

**Comment by ozdeadmeat** [comment]
Which node-red docker image are you using?

**Comment by Markoudstaal** [comment]
Did you send it a private message? Looking at the code and the error you got there might be a bug there.

**Comment by BloodBlight** [comment]
Sorry, I don't recall what type of message it was.
